Repository piro17-Archive/FilmArchive, pull requests merged in 2022-08, with the labels that each got.

#21 [test]머지테스트
  signature_parser.py
Labels: question

#32 [feat] 프레임공유 일주일인기순
  framesharings/migrations/0003_frame_framelikedate.py
  framesharings/migrations/0004_alter_frame_framelikedate.py
  framesharings/migrations/0005_frame_frameweeklike_alter_frame_framelikedate.py
  framesharings/migrations/0006_alter_frame_framelikedate.py
  framesharings/models.py
  framesharings/views.py
  templates/framesharings/frame.html
Labels: 석범, feature

#34 [test]풀리퀘스트 이슈 연동
  framesharings/views.py
Labels: question, 석범

#37 [test]test
  README.md
Labels: question, 석범

#40 [test]test2
  limitedframes/views.py
Labels: question, 석범

#47 [design] 메인페이지 변경
  users/urls.py
Labels: 석범, design

#58 [feat] 프레임 추천찜 ajax
  albums/views.py
  framesharings/urls.py
  framesharings/views.py
  templates/albums/album.html
  templates/albums/albumdetail.html
  templates/framesharings/frame.html
Labels: 석범, feature

#68 [fix] 이슈참고
  framesharings/views.py
  templates/albums/albumdetail.html
  templates/framesharings/framedetail.html
  templates/users/login.html
  users/forms.py
Labels: enhancement, 석범

#73 [design]메인페이지 프레임공유3등
  templates/users/main.html
  users/views.py
Labels: 석범, design

#77 [fix]추천,찜 디자인고침
  templates/framesharings/frame.html
Labels: enhancement, 석범

#80 [fix] 추천css 수정
  templates/framesharings/frame.html
Labels: enhancement, 석범

#86 [fix]캘린더 색상 수정
  templates/albums/albumcalendar.html
Labels: enhancement, 석범

#97 [fix]한정판 오류수정
  templates/limitedframes/limitedlife.html
Labels: enhancement, 석범

#98 Feature/#63 카카오지도 앨범
  albums/migrations/0008_alter_album_albumlocation.py
  albums/migrations/0009_alter_album_albumlocation.py
  albums/migrations/0010_alter_album_albumlocation.py
  albums/migrations/0011_alter_album_albumlocation.py
  albums/migrations/0012_alter_album_albumlocation.py
  albums/migrations/0013_alter_album_albumlocation.py
  albums/models.py
  templates/albums/albumcreate.html
  templates/albums/albumdetail.html
  templates/albums/albumupdate.html
Labels: 석범, feature

#100 [fix] 로그인 실패시 form 사라짐 해결
  templates/users/login.html
  users/views.py
Labels: enhancement, 석범

#116 [fix] 앨범위치 text로
  templates/albums/albumcreate.html
  templates/albums/albumdetail.html
  templates/albums/albumupdate.html
Labels: enhancement, 석범

#118 Feature/#115
  recommends/urls.py
  recommends/views.py
  templates/maps/map.html
  users/views.py
Labels: 석범, feature

#120 [feat] 카카오지도 내주변 검색 목록추가
  templates/maps/map.html
Labels: 석범, feature

#125 [feat]태그선택 수정
  framesharings/views.py
  templates/framesharings/framecreate.html
Labels: 석범, feature

#132 Feat/#131
  templates/users/find_username.html
  templates/users/find_username_complete.html
  templates/users/login.html
  users/forms.py
  users/urls.py
  users/views.py
Labels: feature

#142 [fix] 메인에 지도링크추가
  templates/users/main.html
Labels: enhancement, 석범

#146 [fix] 앨범,프레임공유 사진필수경고
  albums/views.py
  templates/albums/albumcreate.html
  templates/framesharings/framecreate.html
Labels: enhancement, 석범

#150 [fix] settings 수정
  config/settings.py
Labels: enhancement, 석범

#154 Fix/#153
  config/settings.py
  users/forms.py
  users/urls.py
Labels: enhancement, 태윤

#156 [feat] 배포 리눅스 변경사항
  .gitignore
  config/settings.py
  photoism_parser.py
  signature_parser.py
Labels: 석범, feature

#171 Feat/#170
  templates/users/mypage.html
  templates/users/saved_detail.html
  users/urls.py
  users/views.py
Labels: enhancement, 태윤, feature

#172 [fix] 프레임공유 디테일 ajax
  framesharings/views.py
  templates/framesharings/framedetail.html
Labels: enhancement, 태윤

#174 [feat] 카카오지도 주변모든검색,프레임공유 로그인안해도 접근
  static/css/map.css
  static/image/marker_number_blue.png
  static/image/marker_number_blue10.png
  static/image/marker_number_blue11.png
  static/image/marker_number_blue2.png
  static/image/marker_number_blue3.png
  static/image/marker_number_blue4.png
  static/image/marker_number_blue5.png
  static/image/marker_number_blue6.png
  static/image/marker_number_blue7.png
  static/image/marker_number_blue8.png
  static/image/marker_number_blue9.png
  templates/framesharings/frame.html
  templates/maps/map.html
  templates/users/main.html
Labels: 석범, feature

#178 [feat]지도 목록 마우스오버 안움직이게 변경
  templates/maps/map.html
Labels: 석범, feature

#187 [feat]지도 버튼 수정
  static/css/map.css
  templates/maps/map.html
Labels: enhancement, 석범

#190 [fix] 프레임디테일페이지 하트수정
  templates/framesharings/framedetail.html
Labels: enhancement, 석범

#192 [fix] 로그인실패창 생성
  templates/users/login.html
  templates/users/recovery_id.html
  templates/users/signup.html
  users/forms.py
  users/views.py
Labels: enhancement, 태윤

#199 [fix]프레임 디테일 추천수ajax
  templates/framesharings/framedetail.html
Labels: enhancement, 석범

#212 [fix] 프레임 비로그인 수정
  templates/albums/albumcalendar.html
  templates/framesharings/frame.html
Labels: enhancement, 석범

#214 Fix/#213
  templates/users/signup.html
  users/views.py
Labels: enhancement, 태윤

#216 [fix] 로그인 모달창 뜨게 수정
  templates/framesharings/frame.html
Labels: enhancement

#220 [fix] 정렬중인거표시,캘린더 수정, 지도 폰화면 자동이동,삭제수정버튼 생성유저만
  albums/views.py
  framesharings/views.py
  templates/albums/album.html
  templates/albums/albumcalendar.html
  templates/framesharings/frame.html
  templates/framesharings/framedetail.html
  templates/maps/map.html
Labels: enhancement, 석범

#226 [fix] 프레임태그 다중선택, 업데이트수정
  framesharings/views.py
  templates/framesharings/frame.html
  templates/framesharings/frameupdate.html
Labels: enhancement, 석범

#230 [fix] 비밀번호 찾기 에러메세지 생성
  config/settings.py
  templates/registration/password_reset_form.html
  users/forms.py
Labels: enhancement, 태윤

#235 Tag 1.1 배포
  config/settings.py
  static/css/album.css
  static/css/common.css
  static/css/frame.css
  static/css/limitedlife.css
  static/css/login.css
  static/css/mypage.css
  static/css/signup.css
  templates/framesharings/frameupdate.html
  templates/registration/password_reset_form.html
  templates/users/signup.html
  users/forms.py
Labels: enhancement, 석범

#242 [fix] 프레임공유 키워드중복제거
  framesharings/views.py
Labels: enhancement, 석범

#243 Fix/#236
  templates/users/change_pw.html
  users/forms.py
  users/views.py
Labels: enhancement, 태윤

#244 Fix/#234
  static/css/login.css
  templates/registration/password_reset_form.html
  templates/users/change_pw.html
  users/forms.py
  users/views.py
Labels: enhancement, design

#249 Tag 1.2 배포
  framesharings/views.py
  static/css/mypage.css
  static/css/signup.css
  templates/users/saved_detail.html
Labels: enhancement, 석범
